kind = "web"
previewPath = "/"
title = "Quizara"
version = "1.0.0"
id = "artifacts/quizara"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20302

[services.development]
run = "pnpm --filter @workspace/quizara run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/quizara", "run", "build" ]
publicDir = "artifacts/quizara/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20302"
BASE_PATH = "/"
