import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import quizRouter from "./quiz";
import leaderboardRouter from "./leaderboard";
import profileRouter from "./profile";
import adminRouter from "./admin";
import adminEconomyRouter from "./adminEconomy";
import marketplaceRouter from "./marketplace";
import worldsRouter from "./worlds";
import heartsRouter from "./hearts";
import streakRouter from "./streak";
import battlepassRouter from "./battlepass";
import badgesRouter from "./badges";
import challengesRouter from "./challenges";
import wheelRouter from "./wheel";
import blitzRouter from "./blitz";
import dailyTasksRouter from "./dailyTasks";
import playerLibraryRouter from "./playerLibrary";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(quizRouter);
router.use(worldsRouter);
router.use(heartsRouter);
router.use(streakRouter);
router.use(battlepassRouter);
router.use(badgesRouter);
router.use(challengesRouter);
router.use(wheelRouter);
router.use(blitzRouter);
router.use(dailyTasksRouter);
router.use(playerLibraryRouter);
router.use(leaderboardRouter);
router.use(profileRouter);
router.use(adminRouter);
router.use(adminEconomyRouter);
router.use(marketplaceRouter);

export default router;
